# Generated by Django 4.2 on 2024-09-25 18:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crop', models.CharField(blank=True, max_length=100, null=True)),
                ('productivity', models.FloatField(blank=True, null=True)),
                ('area_ha', models.FloatField()),
                ('region', models.CharField(max_length=10, null=True)),
                ('history', models.JSONField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['geometry'], name='fields_fiel_geometr_fc8ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['crop'], name='fields_fiel_crop_b472f8_idx'),
        ),
    ]
