# Generated by Django 4.2 on 2024-09-21 20:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crop', models.CharField(blank=True, max_length=255, null=True)),
                ('productivity', models.FloatField(blank=True, null=True)),
                ('area_ha', models.FloatField()),
                ('region', models.CharField(max_length=50, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
